# /chunktaglimiter reload - перезагрузить этот конфиг, право chunktaglimiter.command

# лимит длины чанка
limit-bytes: 200000

# период запуска таймера проверки чанков на длину
period-ticks: 200

# писать в лог предупреждение, если проверка чанков заняла больше указанного времени
check-warn-time-millis: 5