name: ChunkTagLimiter
version: ${project.version}
main: ua.lokha.chunktaglimiter.Main

# Кодил это? Впиши себя сам
authors: [lokha]

commands:
  chunktaglimiter:
    permission: chunktaglimiter.command